# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: ff54ed718f4fe58055b31de5137d7fb2d92f3cfa
_src_path: gh:netboxlabs/netbox-plugin-scaffold
author_email: support@netboxlabs.com
author_name: NetBox Labs
branching_support: true
commercial: true
current_year: 2026
default_model_name: ''
dev_status: 5 - Production/Stable
django_version: '5.2'
filtersets_layout: flat
forms_layout: type_files
github_org: netboxlabs
layout_style: custom
models_layout: subpackage
netbox_max_version: 4.7.99
netbox_min_version: 4.7.0
netbox_test_max_ref: v4.7.0
netbox_test_min_ref: v4.7.0
package_name: netbox_branching
plugin_name: NetBox Branching
python_version: '3.12'
python_versions:
- '3.12'
- '3.13'
- '3.14'
repo_slug: netbox-branching
ruff_version: 0.15.2
serializers_layout: flat
short_description: A git-like branching implementation for NetBox
tables_layout: subpackage
version: 1.2.1
views_layout: flat
