# Generated by Django 5.0.6 on 2024-06-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_branching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='user',
            new_name='owner',
        ),
    ]
