# Generated by Django 5.2.8 on 2025-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_branching", "0006_tag_object_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="merged_using_collapsed",
            field=models.BooleanField(default=False),
        ),
    ]
