"""
Tests for related models — models that lack ChangeLoggingMixin but must be
replicated per branch because they hold foreign keys into branch-aware tables.
These are listed in INCLUDE_MODELS and would be routed to the main schema
(causing FK violations) if not explicitly included.

Covered models:
  - dcim.cablepath       (auto-generated by trace_paths signal)
  - extras.cachedvalue   (auto-generated by post_save search-indexing signal)
  - extras.taggeditem    (M2M through table for tags)
  - dcim.portmapping     (mapping table for front/rear ports, issue #447)

Note: tenancy.contactgroupmembership was removed in NetBox 4.4 and is no
longer applicable to any supported NetBox version.
"""
import time
import uuid

from dcim.choices import PortTypeChoices
from dcim.models import (
    Cable,
    CablePath,
    Device,
    DeviceRole,
    DeviceType,
    FrontPortTemplate,
    Interface,
    Manufacturer,
    PortMapping,
    PortTemplateMapping,
    RearPortTemplate,
    Site,
)
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.db import connections
from django.test import RequestFactory, TransactionTestCase
from django.urls import reverse
from extras.models import Tag, TaggedItem
from extras.models.search import CachedValue
from netbox.context import current_request
from netbox.context_managers import event_tracking

from netbox_branching.contextvars import active_branch as active_branch_var
from netbox_branching.models import Branch
from netbox_branching.utilities import activate_branch

User = get_user_model()


class RelatedModelsTestCase(TransactionTestCase):
    """
    Verify that related models are routed to the branch schema when a branch
    is active, not to the main schema.
    """
    serialized_rollback = True

    def setUp(self):
        self.user = User.objects.create_user(username='testuser')

        self.manufacturer = Manufacturer.objects.create(name='Manufacturer 1', slug='manufacturer-1')
        self.device_type = DeviceType.objects.create(
            manufacturer=self.manufacturer,
            model='Device Type 1',
            slug='device-type-1',
        )
        self.device_role = DeviceRole.objects.create(name='Device Role 1', slug='device-role-1')
        self.site = Site.objects.create(name='Site 1', slug='site-1')

    def tearDown(self):
        # If a test raised an exception while inside activate_branch() or
        # event_tracking(), those @contextmanager generators never reach their
        # cleanup code.  Reset context vars explicitly so the next test's setUp
        # is not accidentally routed to a stale branch or attributed to a
        # deleted user.
        active_branch_var.set(None)
        current_request.set(None)
        # Close branch schema connections so the test database can be dropped
        # cleanly.  Use the ConnectionHandler's internal thread-local rather
        # than the unreliable hasattr() check to find all initialised aliases.
        for alias in list(vars(connections._connections)):
            if alias.startswith('schema_'):
                connections[alias].close()

    def _provision_branch(self, name='Test Branch'):
        branch = Branch(name=name)
        branch.save(provision=False)
        branch.provision(user=self.user)
        for _ in range(300):
            branch.refresh_from_db()
            if branch.status == 'ready':
                break
            time.sleep(0.1)
        return branch

    def _make_request(self):
        request = RequestFactory().get(reverse('home'))
        request.id = uuid.uuid4()
        request.user = self.user
        return request

    def test_portmapping_routed_to_branch(self):
        """
        Creating a device with front/rear port mappings inside a branch must not
        raise an IntegrityError.  Regression test for issue #447.

        PortMapping lacks ChangeLoggingMixin so without INCLUDE_MODELS the router
        sends bulk_create to the main schema, where the just-created branch device
        does not exist, triggering a FK violation.
        """
        patch_panel_type = DeviceType.objects.create(
            manufacturer=self.manufacturer,
            model='Patch Panel',
            slug='patch-panel',
        )
        rear_port_template = RearPortTemplate.objects.create(
            device_type=patch_panel_type,
            name='Rear Port 1',
            type=PortTypeChoices.TYPE_LC,
        )
        front_port_template = FrontPortTemplate.objects.create(
            device_type=patch_panel_type,
            name='Front Port 1',
            type=PortTypeChoices.TYPE_LC,
        )
        PortTemplateMapping.objects.create(
            front_port=front_port_template,
            front_port_position=1,
            rear_port=rear_port_template,
            rear_port_position=1,
        )

        branch = self._provision_branch()

        with activate_branch(branch), event_tracking(self._make_request()):
            device = Device.objects.create(
                name='Patch Panel Device',
                device_type=patch_panel_type,
                role=self.device_role,
                site=self.site,
            )

        with activate_branch(branch):
            self.assertEqual(PortMapping.objects.filter(device=device).count(), 1)

        # Main schema should have no mapping for this device
        self.assertEqual(PortMapping.objects.filter(device=device).count(), 0)

    def test_taggeditem_routed_to_branch(self):
        """
        Adding tags to an object inside a branch should create TaggedItem records
        in the branch schema, not in the main schema.

        TaggedItem lacks ChangeLoggingMixin so without INCLUDE_MODELS the router
        sends the tag M2M write to the main schema.
        """
        tag = Tag.objects.create(name='Test Tag', slug='test-tag')
        branch = self._provision_branch()

        with activate_branch(branch), event_tracking(self._make_request()):
            site = Site.objects.create(name='Tagged Site', slug='tagged-site')
            site.tags.add(tag)

        site_ct = ContentType.objects.get_for_model(Site)

        with activate_branch(branch):
            self.assertEqual(
                TaggedItem.objects.filter(content_type=site_ct, object_id=site.pk).count(), 1
            )

        # Main schema should have no tag entry for the branch-only site
        self.assertEqual(
            TaggedItem.objects.filter(content_type=site_ct, object_id=site.pk).count(), 0
        )

    def test_cachedvalue_routed_to_branch(self):
        """
        Creating an object inside a branch should write CachedValue search-index
        entries to the branch schema via the post_save signal, not to main.

        CachedValue lacks ChangeLoggingMixin so without INCLUDE_MODELS the router
        sends bulk_create to the main schema.
        """
        branch = self._provision_branch()

        main_count_before = CachedValue.objects.count()

        with activate_branch(branch), event_tracking(self._make_request()):
            site = Site.objects.create(name='Indexed Site', slug='indexed-site')

        site_ct = ContentType.objects.get_for_model(Site)

        with activate_branch(branch):
            self.assertGreater(
                CachedValue.objects.filter(object_type=site_ct, object_id=site.pk).count(), 0
            )

        # Main schema should have no CachedValue for the branch-only site
        self.assertEqual(CachedValue.objects.filter(object_type=site_ct, object_id=site.pk).count(), 0)
        self.assertEqual(CachedValue.objects.count(), main_count_before)

    def test_cablepath_routed_to_branch(self):
        """
        Connecting two interfaces with a cable inside a branch should create
        CablePath records in the branch schema, not in the main schema.

        CablePath lacks ChangeLoggingMixin so without INCLUDE_MODELS the router
        sends the CablePath writes to the main schema.
        """
        with event_tracking(self._make_request()):
            device_a = Device.objects.create(
                name='Device A', device_type=self.device_type,
                role=self.device_role, site=self.site,
            )
            device_b = Device.objects.create(
                name='Device B', device_type=self.device_type,
                role=self.device_role, site=self.site,
            )
            iface_a = Interface.objects.create(device=device_a, name='eth0', type='1000base-t')
            iface_b = Interface.objects.create(device=device_b, name='eth0', type='1000base-t')

        branch = self._provision_branch()

        with activate_branch(branch):
            self.assertEqual(CablePath.objects.count(), 0)

        with activate_branch(branch), event_tracking(self._make_request()):
            cable = Cable(
                a_terminations=[Interface.objects.get(pk=iface_a.pk)],
                b_terminations=[Interface.objects.get(pk=iface_b.pk)],
            )
            cable.save()

        with activate_branch(branch):
            self.assertEqual(CablePath.objects.count(), 2)

        # Main schema should still have no cable paths
        self.assertEqual(CablePath.objects.count(), 0)
